# Generated by Django 5.1.6 on 2025-02-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMDRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_number', models.IntegerField()),
                ('co', models.IntegerField()),
                ('time', models.TimeField()),
                ('start', models.DateTimeField()),
                ('direction', models.CharField(max_length=10)),
                ('cli', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
